"""
Report Generation Service
Generates multilingual PDF reports for dropout prediction simulations
Supports English, Hindi, and Rajasthani languages
"""

import os
import logging
from pathlib import Path
from datetime import datetime
from typing import Dict, Any, List
from fpdf import FPDF

logger = logging.getLogger(__name__)

# Multilingual translations dictionary
TRANSLATIONS = {
    "en": {
        "title": "Dropout Risk Assessment Report",
        "subtitle": "AI-Based Student Risk Prediction System",
        "report_date": "Report Date",
        "simulation_id": "Simulation ID",
        "student_info": "Student Information",
        "enrollment": "Enrollment Number",
        "gender": "Gender",
        "academic_info": "Academic Information",
        "attendance": "Attendance",
        "cgpa": "CGPA",
        "backlogs": "Number of Backlogs",
        "marks_10th": "10th Grade Marks",
        "marks_12th": "12th Grade Marks",
        "financial_info": "Financial & Disciplinary Information",
        "fees_status": "Fees Payment Status",
        "suspension_status": "Suspension Status",
        "paid": "Paid",
        "unpaid": "Unpaid",
        "no_suspension": "No Suspension",
        "suspended": "Suspended",
        "prediction_results": "Prediction Results",
        "ml_prediction": "ML Model Prediction",
        "final_prediction": "Final Risk Level",
        "ml_probability": "Dropout Probability",
        "rule_override": "Rule Override Applied",
        "yes": "Yes",
        "no": "No",
        "risk_levels": "Risk Level Classification",
        "risk_green": "Green - Low Risk: Student is performing well with minimal dropout risk",
        "risk_yellow": "Yellow - Moderate Risk: Student shows some warning signs requiring attention",
        "risk_orange": "Orange - High Risk: Student requires immediate intervention and counseling",
        "risk_red": "Red - Critical Risk: Student at severe risk of dropout, urgent action needed",
        "recommendations": "Recommendations",
        "rec_green": "Continue monitoring academic performance. Encourage maintaining current standards.",
        "rec_yellow": "Schedule regular counseling sessions. Monitor attendance and academic progress closely.",
        "rec_orange": "Immediate intervention required. Arrange counseling, academic support, and family meetings.",
        "rec_red": "Critical intervention needed. Engage with student, family, and administration urgently.",
        "footer": "Generated by AI-Based Dropout Prediction System",
        "confidential": "CONFIDENTIAL - For Official Use Only",
        "page": "Page"
    },
    "hi": {
        "title": "ड्रॉपआउट जोखिम मूल्यांकन रिपोर्ट",
        "subtitle": "एआई-आधारित छात्र जोखिम पूर्वानुमान प्रणाली",
        "report_date": "रिपोर्ट तिथि",
        "simulation_id": "सिमुलेशन आईडी",
        "student_info": "छात्र जानकारी",
        "enrollment": "नामांकन संख्या",
        "gender": "लिंग",
        "academic_info": "शैक्षणिक जानकारी",
        "attendance": "उपस्थिति",
        "cgpa": "सीजीपीए",
        "backlogs": "बैकलॉग की संख्या",
        "marks_10th": "10वीं कक्षा के अंक",
        "marks_12th": "12वीं कक्षा के अंक",
        "financial_info": "वित्तीय और अनुशासनात्मक जानकारी",
        "fees_status": "फीस भुगतान स्थिति",
        "suspension_status": "निलंबन स्थिति",
        "paid": "भुगतान किया",
        "unpaid": "बकाया",
        "no_suspension": "कोई निलंबन नहीं",
        "suspended": "निलंबित",
        "prediction_results": "पूर्वानुमान परिणाम",
        "ml_prediction": "एमएल मॉडल पूर्वानुमान",
        "final_prediction": "अंतिम जोखिम स्तर",
        "ml_probability": "ड्रॉपआउट संभावना",
        "rule_override": "नियम ओवरराइड लागू",
        "yes": "हाँ",
        "no": "नहीं",
        "risk_levels": "जोखिम स्तर वर्गीकरण",
        "risk_green": "हरा - कम जोखिम: छात्र अच्छा प्रदर्शन कर रहा है, न्यूनतम ड्रॉपआउट जोखिम",
        "risk_yellow": "पीला - मध्यम जोखिम: छात्र में कुछ चेतावनी संकेत हैं, ध्यान की आवश्यकता है",
        "risk_orange": "नारंगी - उच्च जोखिम: छात्र को तत्काल हस्तक्षेप और परामर्श की आवश्यकता है",
        "risk_red": "लाल - गंभीर जोखिम: छात्र को ड्रॉपआउट का गंभीर खतरा, तत्काल कार्रवाई आवश्यक",
        "recommendations": "सिफारिशें",
        "rec_green": "शैक्षणिक प्रदर्शन की निगरानी जारी रखें। वर्तमान मानकों को बनाए रखने के लिए प्रोत्साहित करें।",
        "rec_yellow": "नियमित परामर्श सत्र निर्धारित करें। उपस्थिति और शैक्षणिक प्रगति की बारीकी से निगरानी करें।",
        "rec_orange": "तत्काल हस्तक्षेप आवश्यक। परामर्श, शैक्षणिक सहायता और परिवार की बैठकों की व्यवस्था करें।",
        "rec_red": "गंभीर हस्तक्षेप की आवश्यकता। छात्र, परिवार और प्रशासन के साथ तत्काल संपर्क करें।",
        "footer": "एआई-आधारित ड्रॉपआउट पूर्वानुमान प्रणाली द्वारा उत्पन्न",
        "confidential": "गोपनीय - केवल आधिकारिक उपयोग के लिए",
        "page": "पृष्ठ"
    },
    "rj": {
        "title": "ड्रॉपआउट खतरो मूल्यांकन रिपोर्ट",
        "subtitle": "एआई-आधारित छात्र खतरो भविष्यवाणी प्रणाली",
        "report_date": "रिपोर्ट री तारीख",
        "simulation_id": "सिमुलेशन आईडी",
        "student_info": "छात्र री जाणकारी",
        "enrollment": "नामांकन नंबर",
        "gender": "लिंग",
        "academic_info": "पढ़ाई री जाणकारी",
        "attendance": "हाजिरी",
        "cgpa": "सीजीपीए",
        "backlogs": "बैकलॉग री संख्या",
        "marks_10th": "10वीं कक्षा रा अंक",
        "marks_12th": "12वीं कक्षा रा अंक",
        "financial_info": "आर्थिक अर अनुशासनात्मक जाणकारी",
        "fees_status": "फीस भुगतान री स्थिति",
        "suspension_status": "निलंबन री स्थिति",
        "paid": "भुगतान हो ग्यो",
        "unpaid": "बाकी है",
        "no_suspension": "कोई निलंबन कोनी",
        "suspended": "निलंबित",
        "prediction_results": "भविष्यवाणी परिणाम",
        "ml_prediction": "एमएल मॉडल भविष्यवाणी",
        "final_prediction": "अंतिम खतरो स्तर",
        "ml_probability": "ड्रॉपआउट संभावना",
        "rule_override": "नियम ओवरराइड लागू",
        "yes": "हां",
        "no": "ना",
        "risk_levels": "खतरो स्तर वर्गीकरण",
        "risk_green": "हरो - कम खतरो: छात्र सारो काम कर रह्यो है, कम ड्रॉपआउट खतरो",
        "risk_yellow": "पीलो - मध्यम खतरो: छात्र में कुछ चेतावनी संकेत हैं, ध्यान री जरूरत है",
        "risk_orange": "नारंगी - ऊंचो खतरो: छात्र नै तुरंत हस्तक्षेप अर परामर्श री जरूरत है",
        "risk_red": "लाल - गंभीर खतरो: छात्र नै ड्रॉपआउट रो गंभीर खतरो, तुरंत कार्रवाई जरूरी",
        "recommendations": "सिफारिशां",
        "rec_green": "पढ़ाई री निगरानी जारी राखो। वर्तमान मानकां नै बणाए राखण खातर प्रोत्साहित करो।",
        "rec_yellow": "नियमित परामर्श सत्र तय करो। हाजिरी अर पढ़ाई री प्रगति री बारीकी सूं निगरानी करो।",
        "rec_orange": "तुरंत हस्तक्षेप जरूरी। परामर्श, पढ़ाई री मदद अर परिवार री बैठकां री व्यवस्था करो।",
        "rec_red": "गंभीर हस्तक्षेप री जरूरत। छात्र, परिवार अर प्रशासन सूं तुरंत संपर्क करो।",
        "footer": "एआई-आधारित ड्रॉपआउट भविष्यवाणी प्रणाली सूं बणायो",
        "confidential": "गोपनीय - केवल आधिकारिक उपयोग खातर",
        "page": "पन्नो"
    }
}

# Risk level color codes
RISK_COLORS = {
    "Green": (34, 197, 94),    # Green
    "Yellow": (234, 179, 8),   # Yellow
    "Orange": (249, 115, 22),  # Orange
    "Red": (239, 68, 68)       # Red
}


class ReportPDF(FPDF):
    """Custom PDF class with header and footer"""
    
    def __init__(self, language: str = "en"):
        super().__init__()
        self.language = language
        self.translations = TRANSLATIONS.get(language, TRANSLATIONS["en"])
        
    def header(self):
        """Add header to each page"""
        # Logo placeholder (you can add actual logo if available)
        # self.image('logo.png', 10, 8, 33)
        
        # Title
        self.set_font('Arial', 'B', 16)
        self.set_text_color(30, 64, 175)  # Blue color
        self.cell(0, 10, self.translations["title"], 0, 1, 'C')
        
        # Subtitle
        self.set_font('Arial', 'I', 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 5, self.translations["subtitle"], 0, 1, 'C')
        
        # Line break
        self.ln(5)
        
    def footer(self):
        """Add footer to each page"""
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        
        # Page number
        self.cell(0, 10, f'{self.translations["page"]} {self.page_no()}', 0, 0, 'C')
        
    def chapter_title(self, title: str, color: tuple = (0, 0, 0)):
        """Add a chapter title"""
        self.set_font('Arial', 'B', 12)
        self.set_text_color(*color)
        self.cell(0, 10, title, 0, 1, 'L')
        self.set_text_color(0, 0, 0)
        self.ln(2)
        
    def chapter_body(self, label: str, value: str):
        """Add a body text with label and value"""
        self.set_font('Arial', 'B', 10)
        self.cell(60, 8, label + ':', 0, 0, 'L')
        self.set_font('Arial', '', 10)
        self.cell(0, 8, str(value), 0, 1, 'L')
        
    def add_risk_box(self, risk_level: str):
        """Add a colored box showing the risk level"""
        color = RISK_COLORS.get(risk_level, (100, 100, 100))
        
        # Draw colored rectangle
        self.set_fill_color(*color)
        self.set_text_color(255, 255, 255)
        self.set_font('Arial', 'B', 14)
        
        # Center the box
        box_width = 100
        x = (self.w - box_width) / 2
        self.set_x(x)
        
        self.cell(box_width, 12, risk_level.upper(), 1, 1, 'C', True)
        self.set_text_color(0, 0, 0)
        self.ln(5)


def generate_report_pdf(
    simulation_data: Dict[str, Any],
    prediction_result: Dict[str, Any],
    simulation_id: str,
    language: str = "en"
) -> str:
    """
    Generate a PDF report for a simulation
    
    Args:
        simulation_data: Input data from simulation
        prediction_result: Prediction results
        simulation_id: Unique simulation identifier
        language: Report language (en, hi, rj)
        
    Returns:
        Path to generated PDF file
    """
    try:
        translations = TRANSLATIONS.get(language, TRANSLATIONS["en"])
        
        # Create PDF
        pdf = ReportPDF(language)
        pdf.add_page()
        
        # Report metadata
        pdf.set_font('Arial', 'I', 9)
        pdf.set_text_color(100, 100, 100)
        current_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        pdf.cell(0, 6, f"{translations['report_date']}: {current_date}", 0, 1, 'R')
        pdf.cell(0, 6, f"{translations['simulation_id']}: {simulation_id}", 0, 1, 'R')
        pdf.ln(5)
        
        # Confidential notice
        pdf.set_font('Arial', 'B', 9)
        pdf.set_text_color(239, 68, 68)
        pdf.cell(0, 6, translations["confidential"], 0, 1, 'C')
        pdf.set_text_color(0, 0, 0)
        pdf.ln(5)
        
        # Student Information
        pdf.chapter_title(translations["student_info"], (30, 64, 175))
        pdf.chapter_body(translations["enrollment"], simulation_data.get("enrollment_no", "N/A"))
        pdf.chapter_body(translations["gender"], simulation_data.get("gender", "N/A"))
        pdf.ln(3)
        
        # Academic Information
        pdf.chapter_title(translations["academic_info"], (30, 64, 175))
        pdf.chapter_body(translations["attendance"], f"{simulation_data.get('attendance', 0):.1f}%")
        pdf.chapter_body(translations["cgpa"], f"{simulation_data.get('cgpa', 0):.2f}/10")
        pdf.chapter_body(translations["backlogs"], str(simulation_data.get("backlogs", 0)))
        pdf.chapter_body(translations["marks_10th"], f"{simulation_data.get('marks_10th', 0):.1f}%")
        pdf.chapter_body(translations["marks_12th"], f"{simulation_data.get('marks_12th', 0):.1f}%")
        pdf.ln(3)
        
        # Financial & Disciplinary Information
        pdf.chapter_title(translations["financial_info"], (30, 64, 175))
        fees_status = translations["paid"] if simulation_data.get("fees_flag", 0) == 0 else translations["unpaid"]
        suspension_status = translations["no_suspension"] if simulation_data.get("suspension_flag", 0) == 0 else translations["suspended"]
        pdf.chapter_body(translations["fees_status"], fees_status)
        pdf.chapter_body(translations["suspension_status"], suspension_status)
        pdf.ln(5)
        
        # Prediction Results
        pdf.chapter_title(translations["prediction_results"], (220, 38, 38))
        
        # Risk level box
        final_phase = prediction_result.get("final_phase", "Unknown")
        pdf.add_risk_box(final_phase)
        
        pdf.chapter_body(translations["ml_prediction"], prediction_result.get("model_phase", "N/A"))
        pdf.chapter_body(translations["final_prediction"], final_phase)
        
        if prediction_result.get("ml_probability") is not None:
            probability = prediction_result.get("ml_probability", 0) * 100
            pdf.chapter_body(translations["ml_probability"], f"{probability:.1f}%")
        
        rule_override = translations["yes"] if prediction_result.get("rule_override", False) else translations["no"]
        pdf.chapter_body(translations["rule_override"], rule_override)
        
        if prediction_result.get("override_reason"):
            pdf.ln(2)
            pdf.set_font('Arial', 'I', 9)
            pdf.set_text_color(100, 100, 100)
            pdf.multi_cell(0, 5, prediction_result.get("override_reason", ""))
            pdf.set_text_color(0, 0, 0)
        
        pdf.ln(5)
        
        # Risk Levels Explanation
        pdf.chapter_title(translations["risk_levels"], (30, 64, 175))
        pdf.set_font('Arial', '', 9)
        
        for risk, desc_key in [
            ("Green", "risk_green"),
            ("Yellow", "risk_yellow"),
            ("Orange", "risk_orange"),
            ("Red", "risk_red")
        ]:
            color = RISK_COLORS[risk]
            pdf.set_fill_color(*color)
            pdf.set_text_color(255, 255, 255)
            pdf.cell(20, 6, risk, 0, 0, 'C', True)
            pdf.set_text_color(0, 0, 0)
            pdf.set_font('Arial', '', 8)
            pdf.cell(0, 6, translations[desc_key], 0, 1, 'L')
            pdf.set_font('Arial', '', 9)
        
        pdf.ln(5)
        
        # Recommendations
        pdf.chapter_title(translations["recommendations"], (22, 163, 74))
        pdf.set_font('Arial', '', 9)
        
        # Get recommendation based on risk level
        rec_key = f"rec_{final_phase.lower()}"
        if rec_key in translations:
            pdf.multi_cell(0, 6, translations[rec_key])
        
        pdf.ln(5)
        
        # Footer text
        pdf.set_font('Arial', 'I', 8)
        pdf.set_text_color(128, 128, 128)
        pdf.cell(0, 6, translations["footer"], 0, 1, 'C')
        
        # Save PDF
        reports_dir = Path(__file__).parent.parent / "reports" / simulation_id
        reports_dir.mkdir(parents=True, exist_ok=True)
        
        output_path = reports_dir / f"report_{language}.pdf"
        pdf.output(str(output_path))
        
        logger.info(f"Generated {language} report: {output_path}")
        return str(output_path)
        
    except Exception as e:
        logger.error(f"Error generating {language} PDF report: {e}")
        raise


def generate_all_reports(
    simulation_data: Dict[str, Any],
    prediction_result: Dict[str, Any],
    simulation_id: str
) -> List[str]:
    """
    Generate reports in all three languages
    
    Args:
        simulation_data: Input data from simulation
        prediction_result: Prediction results
        simulation_id: Unique simulation identifier
        
    Returns:
        List of paths to generated PDF files
    """
    report_paths = []
    
    for language in ["en", "hi", "rj"]:
        try:
            path = generate_report_pdf(
                simulation_data,
                prediction_result,
                simulation_id,
                language
            )
            report_paths.append(path)
        except Exception as e:
            logger.error(f"Failed to generate {language} report: {e}")
            
    return report_paths


def cleanup_old_reports(days: int = 7):
    """
    Clean up reports older than specified days
    
    Args:
        days: Number of days to keep reports
    """
    try:
        reports_dir = Path(__file__).parent.parent / "reports"
        if not reports_dir.exists():
            return
            
        cutoff_time = datetime.now().timestamp() - (days * 24 * 60 * 60)
        
        for report_folder in reports_dir.iterdir():
            if report_folder.is_dir():
                folder_time = report_folder.stat().st_mtime
                if folder_time < cutoff_time:
                    import shutil
                    shutil.rmtree(report_folder)
                    logger.info(f"Deleted old report folder: {report_folder}")
                    
    except Exception as e:
        logger.error(f"Error cleaning up old reports: {e}")
